export * from "./schema.js";
export * from "./contract.js";
export { parsePolicy, defaultPolicy, grantForTool } from "./parse.js";
export type { ResolvedPolicy, ParseResult, ParseOptions, PolicyError } from "./parse.js";
export { canonicalizePath, canonicalizeRoot, contains, defaultCaseInsensitive, nodeFsProbe } from "./containment.js";
export type { Canonical, CanonicalizeOptions, FsProbe } from "./containment.js";
export { evaluateUrl, evaluateHost, extractUrls, isIpLiteral, isPrivateAddress, ANY_HOST } from "./hosts.js";
export type { UrlDecision, HostAllowlist } from "./hosts.js";
export { evaluateEgressTarget, scanForUrls, dedupeTargets } from "./egress.js";
export type { EgressTarget, EgressOutcome, EgressTargetKind, EgressDiscovery } from "./egress.js";
export { scanRequestedSchema, tokenize } from "./credentials.js";
export type { CredentialScan, CredentialMatch, CredentialConfidence } from "./credentials.js";
export { resolveAnnotations, assessMutation } from "./annotations.js";
export type { ResolvedAnnotations, MutationAssessment } from "./annotations.js";
export { collectRoleTargets, deriveUrlSelectors, hasAnyRole } from "./roles.js";
export type { Role, RoleTarget } from "./roles.js";
export { inferProfile, inferredPolicy, exercisedCapabilities, SessionObserver, INFERRED_SCHEMES } from "./infer.js";
export type { CapabilityProfile, InferenceOptions, InferenceReason, InferenceSignal, InferredPolicy, ObservationMode, ObservationWindow } from "./infer.js";
